export const tractJoined =
  "https://dcoszmf9no5hj.cloudfront.net/data-query/653bfcc7a723810008c2c81e";
export const months = [
  "01",
  "02",
  "03",
  "04",
  "05",
  "06",
  "07",
  "08",
  "09",
  "10",
  "11",
  "12",
];
export const years = ["2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023"];
export const complaints = [
  "Other",
  "Pavement Maintenance",
  "Traffic Signal Timing",
  "Encampment",
  "Street Light Maintenance",
  "Traffic Signal Issue",
  "Street Flooded",
  "Stormwater",
  "Tree Maintenance",
  "Pothole",
  "Parking",
  "Illegal Dumping",
  "Graffiti - Public",
  "Environmental Services Code Compliance",
  "Missed Collection",
  "Parks Issue",
  "Street Sweeping",
  "Traffic Sign Maintenance",
  "ROW Maintenance",
  "Graffiti - Code Enforcement",
  "Stormwater Code Enforcement",
  "Sidewalk Repair Issue",
  "Parking Violation",
  "Waste on Private Property",
  "Shared Mobility Device",
  "Traffic Engineering",
  "Development Services - Code Enforcement",
  "Dead Animal",
  "Vegetation Encroachment",
  "Trash/Recycling Collection",
  "Weed Cleanup",
  "Right-of-Way Code Enforcement",
];
export const walkAuditNames = [
  '"No Riding Bikes on Sidewalk" Sign, but no bike infrastructure',
  "10 Second Crossing Window",
  "10 second crossing window",
  "12th & Imperial Transit Center",
  "4-Way Stop",
  "4394 Mayberry St, San Diego, CA 92113, USA",
  "4853 Bunnell St, San Diego, CA 92113, USA",
  "4855 Ocean View Blvd, San Diego, CA 92113, USA",
  "932 Delta St, National City, CA 91950, USA",
  "Aggressive Drivers",
  "Audible Crossing",
  "Audible Pedestrian Crossing Signal",
  "Audible Pedestrian Signal",
  "Audible RRFB",
  "Audible Signal",
  "Beg Button Obscured",
  "Bicycle Lane",
  "Bike Lane",
  "Bike Lane Starts Here",
  "Bike Parking",
  "Bike Rack",
  "Bike lanes",
  "Broken Sidewalk",
  "Broken/Narrow Sidewalks",
  "Broken/Uneven Sidewalks",
  "Broken/narrow Sidewalk",
  "Bus Only Lane",
  "Cars Parked on Curb",
  "Cars Roll Stop",
  "Cars do not yield to pedestrians",
  "Chicano Park",
  "Chicano Park Museum and Cultural Center",
  "Construction",
  "County Center/Little Italy Station",
  "Cracked Sidewalk",
  "Cracked Sidewalks",
  "Crosswalks",
  "Curb Extension",
  "Curb Should be Painted Red",
  "Cycle Track",
  "Debris",
  "Debris on Sidewalk",
  "Diverters",
  "Division St & Highland Av, National City, CA 91950, USA",
  "Drivers Speeding",
  "Empty Lot",
  "Euclid Elementary School",
  "Excess Litter",
  "Faded Crosswalk",
  "Faded Crosswalk Paint",
  "Faded School Crosswalks",
  "Faded crosswalk",
  "Faded/ Missing Crosswalks",
  "Faded/Missing Crosswalk",
  "Faded/Missing Crosswalks",
  "Father Joe's",
  "Father Joe's\xa0",
  "Flooding",
  "Flooding Issues",
  "Former car crash",
  "Fridge in Curb Ramp",
  "High Visibility Crosswalk",
  "Hill",
  "Insufficient Street Lighting",
  "Intersection Mural",
  "Keeler Court Apartments",
  "Kennedy Neighborhood Park",
  "Lack of Lighting",
  "Las Serenas Apartments",
  "Las Serenas Apartments, Delta Street, San Diego, CA, USA",
  "Lincoln Senior High School",
  "Litter",
  "Little Italy",
  "Long Light, hard to catch bus",
  "Long Signals, Short Crossing Windows",
  "Marriott Marquis San Diego Marina",
  "Mayberry Street & South 44th Street, San Diego, CA, USA",
  "Mayberry Townhomes",
  "Memorial Dog Park",
  "Mid-Block Crossing",
  "Midblock Crossing",
  "Missing Crosswalk",
  "Missing Crosswalks",
  "Missing Curb Ramp",
  "Missing Sidewalk",
  "Missing/Broken Sidewalks",
  "Montgomery Middle School",
  "Mural",
  "Murals",
  "Murals/Art",
  "Narrow Sidewalk",
  "Narrow Sidewalks",
  "Narrow/ Broken Sidewalks",
  "No Audible Pedestrian Crossing Signals",
  "No Bench or Shade Bus Stop",
  "No Crossing",
  "No Crosswalk",
  "No Crosswalks or Stoppages",
  "No Crosswalk\xa0",
  "No Curb Ramp",
  "No Ramp",
  "No Ramp or Crosswalk",
  "No Ramps",
  "No School Crossing Markings",
  "No Shade",
  "No Shade Bus Stop",
  "No Sidewalk",
  "No Truncated Domes",
  "No crosswalk",
  "Nobel Drive Station",
  "Not Enough Time to Cross",
  "Obstruction",
  "Obstructions/Trash",
  "Only one crosswalk, no vehicle stoppage",
  "Overgrown Path",
  "Pacific Beach Middle School",
  "Pacific Beach Taylor Branch Library",
  "Paradise Senior Center",
  "Parking obscures line of sight during drop off and pick up, teachers would like no parking during x hours signage",
  "Parklets",
  "Pedestrian Median",
  "Pedestrian Refuge Island",
  "Pedestrian Scale Lighting",
  "Point 20",
  "Polk Avenue",
  "Poor Lighting",
  "Protected Pedestrian Promenade",
  "Rapid Flashing Beacon",
  "Rapid Flashing Beacon (RRFB)",
  "Route",
  "San Diego College of Continuing Education",
  "San Diego Convention Center",
  "Santa Fe Depot",
  "School Entrance",
  "Seaport Village",
  "Separated Bike Lane",
  "Shade",
  "Shaded Sidewalk",
  "Sharrow",
  "Sheltered Bus Stop",
  "Short Crossing Signal",
  "Short Crossing Time",
  "Sidewalk Obstruction",
  "Sidewalk Obstructions",
  "Speed Bump",
  "Speeding Cars",
  "Speeding Vehicles",
  "St. Rita's Catholic School",
  "Starting Point",
  "Teralta Park",
  "Traffic lights malfuctioning",
  "Trash",
  "Trash\xa0",
  "Tree Cover, Wide Sidewalks",
  "Trees",
  "Trees/ Shade",
  "Trees/Shade",
  "Uneven Sidewalk",
  "Uneven Sidewalks",
  "University Avenue",
  "Unusable Sidewalk",
  "Walk Audit Route",
  "Walk Audit Start Location",
  "Walking Route",
  "Walking route",
  "Waterfront Park",
  "Wayfinding Sign",
  "Weeds and Graffiti",
  "Wide Sidewalk",
  "Wide Sidewalks",
  "Witnessed Jaywalking",
  "Yellow Crosswalk",
  "Zebra Crosswalks",
];

export const dates = (() => {
  let dates: string[] = [];
  years.forEach((year) => {
    months.forEach((month) => {
      dates.push(`${year}-${month}`);
    });
  });
  return dates;
})();

export const raw311 =
  "https://dcoszmf9no5hj.cloudfront.net/data-query/653be6b05ff01600085e5eef";
export const walkAudits =
  "https://dcoszmf9no5hj.cloudfront.net/data-query/653bf1235ecf29000896210d";

export const lineData =
  "https://dcoszmf9no5hj.cloudfront.net/data-query/653bf6dbc5ea2b0008cd63c0";
