export const abbrs = [
  "*",
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  // "CZ",
  "CO",
  "CT",
  "DE",
  "DC",
  "FL",
  "GA",
  "GU",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "PR",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VI",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
];
export const specialties = [
  { value: "*", label: "All" },
  { value: "%207W00000X%", label: "Ophthalmology: " },
  {
    value: "%207WX0120X%",
    label: "Ophthalmology: Cornea and External Diseases Specialist",
  },
  { value: "%207WX0009X%", label: "Ophthalmology: Glaucoma Specialist" },
  { value: "%207WX0109X%", label: "Ophthalmology: Neuro-ophthalmology" },
  {
    value: "%207WX0200X%",
    label: "Ophthalmology: Ophthalmic Plastic and Reconstructive Surgery",
  },
  {
    value: "%207WX0110X%",
    label: "Ophthalmology: Pediatric Ophthalmology and Strabismus Specialist",
  },
  { value: "%207WX0107X%", label: "Ophthalmology: Retina Specialist" },
  {
    value: "%207WX0108X%",
    label: "Ophthalmology: Uveitis and Ocular Inflammatory Disease",
  },
  { value: "%152W00000X%", label: "Optometrist: " },
  {
    value: "%152WC0802X%",
    label: "Optometrist: Corneal and Contact Management",
  },
  { value: "%152WL0500X%", label: "Optometrist: Low Vision Rehabilitation" },
  { value: "%152WX0102X%", label: "Optometrist: Occupational Vision" },
  { value: "%152WP0200X%", label: "Optometrist: Pediatrics" },
  { value: "%152WS0006X%", label: "Optometrist: Sports Vision" },
  { value: "%152WV0400X%", label: "Optometrist: Vision Therapy" },
  { value: "%156F00000X%", label: "Technician\\/Technologist: " },
  { value: "%156FC0800X%", label: "Technician\\/Technologist: Contact Lens" },
  {
    value: "%156FC0801X%",
    label: "Technician\\/Technologist: Contact Lens Fitter",
  },
  { value: "%156FX1700X%", label: "Technician\\/Technologist: Ocularist" },
  { value: "%156FX1100X%", label: "Technician\\/Technologist: Ophthalmic" },
  {
    value: "%156FX1101X%",
    label: "Technician\\/Technologist: Ophthalmic Assistant",
  },
  { value: "%156FX1800X%", label: "Technician\\/Technologist: Optician" },
  {
    value: "%156FX1201X%",
    label: "Technician\\/Technologist: Optometric Assistant",
  },
  {
    value: "%156FX1202X%",
    label: "Technician\\/Technologist: Optometric Technician",
  },
  { value: "%156FX1900X%", label: "Technician\\/Technologist: Orthoptist" },
];
export const statTable = JSON.stringify([
  "providers_per_100k",
  "providers_count",
  "Vision Difficulty Rate",
  "Percent Without Health Insurance",
  "Percent Less than High School",
  "Total Population",
]);
export const bothDatasets = JSON.stringify([
  "https://d36q6zt0rhsb35.cloudfront.net/data-query/65303831181b4500089e4fe6",
  "https://d36q6zt0rhsb35.cloudfront.net/data-query/65303b14fc2a290008152629",
]);
export const tableColumns = JSON.stringify([
  "NPI",
  "Provider First Name",
  "Provider Last Name (Legal Name)",
  "Provider Credential Text",
  "Full Address",
  "Taxonomy",
  "County Name",
  "Congressional District GEOID",
  "Zip Code (ZCTA)",
  "County GEOID",
]);
export const tooltipSpec = JSON.stringify([
  {
    column: "NAME",
    label: "County",
  },
  {
    column: "providers_per_100k",
    label: "Providers / 100k Pop",
  },
  {
    column: "providers_count",
    label: "Total Providers",
  },
  {
    column: "Total Population",
  },
  {
    column: "Vision Difficulty Rate",
    format: "percent",
  },
  {
    column: "Percent Less than High School",
    format: "percent",
  },
  {
    column: "Percent Without Health Insurance",
    format: "percent",
  },
]);